### PR TITLE
Added request for enabling push notifications

### PR DESCRIPTION
**Pull request by tilowestermann**
This adds a pre-request in order to enable push notifications.

### CODE REVIEW

**Comment by tilowestermann** [comment]
Thanks for the comments. 

I added the missing parts, i.e.
- iOS7 (and below) compatibility
- granular request types
- check for denied requests (f the actual request is shown, a UIApplicationWillResignActive notification is fired. if the user then selects one option, a UIApplicationDidBecomeActive notification is fired <= listening for this one and calling firePushNotificationPermissionCompletionHandler)

**Comment by Kraignos** [comment]
The asynchronous issue can be solved. In the right method according to the iOS version "didRegisterUserNotificationSettings" or "didRegisterForRemoteNotificationsWithDeviceToken", you post a notification on which the ClusterPrePermission is listening to, and thus calls the firePushNotificationPermissionCompletionHandler. And that's it.

**Comment by tilowestermann** [comment]
I think that this is exactly what @rsattar didn't want to do, as you would need to post these notifications from the app delegate. My second commit tries to solve this issue by observing a `UIApplicationDidBecomeActive` notification, which will be fired after the user closes the actual permission request (i.e. choosing yes/no)

**Comment by confile** [comment]
Is there work going on on this pull request? Is it working on iOS7 and IOS8 or not?

**Comment by tilowestermann** [comment]
@confile I created [APNPermissionRequest](https://github.com/tilowestermann/APNPermissionRequest). This is based on the idea of `ClusterPrePermissions`, but also adds optional notification settings directly to the request. It is working on iOS7+.

**Pull request closed without merging**
