### PR TITLE
Fix difference between Video and Mic permissions

### PR DESCRIPTION
**Pull request by tkorsi**
You can have your mic be turned off in Settings.app
But permission will still give you hasPermission=TRUE 
Now fixed

### CODE REVIEW

**Comment by confile** [comment]
+1

**Comment by rsattar** [comment]
Seems like this fix also adds push notification support. Would love to fix the video/mic permission issue first, then handle the push notifications.

**Comment by confile** [comment]
@tkorsi Could you please separate your pull request and put the push part in a other pull request?
Thanks!

**Comment by imothee** [comment]
Bumping this thread, if @tkorsi doesn't have a chance to get to this I'll merge his commits into separate pull requests and submit them so he still gets credit.

**Comment by rsattar** [comment]
@tkorsi @imothee @confile I didn't merge this because of the push notification related changes, so I've committed the fix myself. Updated to 0.6.0.

**Comment by imothee** [comment]
Thanks but the push notifications part was the one I was most interested in. Do you have any plans to add that per #19 ?

**Comment by confile** [comment]
@rsattar Still push permissions are missing. Do you have plans to add them?

**Pull request closed without merging**
